import NavBar from '../components/NavBar'
import Parallax from '../components/Parallax'


export default function Home() {
	return <div>
		<NavBar />
		<Parallax />
		<div className='contents'>
			<header>
				<h1>Software Developer</h1>
			</header>
			<div className='inner'>
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />
			lorem <br />


</div>
		</div>
	</div>

}
